# These values apply to the preprod environment, and overrides config in values.yaml
# as needed.
#
# This values file is applied on each deployment to the environment by AWS Codepipeline.
#
env:
  XYZ_ENV: preprod
  MONGO_URL: mongodb+srv://commonplace-preprod-pre-prod-pl-0.rcb9r.mongodb.net?retryWrites=true&w=3&readPreference=nearest
  DBS_XYZ: postgres://mappreprod.ct36hfcslmg5.eu-west-2.rds.amazonaws.com/map
  NEW_RELIC_LICENSE_KEY: eu01xx97418170c5ac03c17292a6b215c022NRAL

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 200
  targetMemoryUtilizationPercentage: 200
