# These values apply to the production environment, and overrides config in values.yaml
# as needed.
#
# This values file is applied on each deployment to the environment by AWS Codepipeline.
#
env:
  XYZ_ENV: production
  MONGODB_URL: mongodb+srv://cp-pl-0.lfxwi.mongodb.net?retryWrites=true&w=3&readPreference=nearest

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 200
  targetMemoryUtilizationPercentage: 200
