# These values apply to the staging environment, and overrides config in values.yaml
# as needed.
#
# This values file is applied on each deployment to the environment by AWS Codepipeline.
#
env:
  XYZ_ENV: staging
  MONGO_URL: mongodb+srv://cp-non-prod-pl-1.lfxwi.mongodb.net?retryWrites=true&w=3&readPreference=nearest
  DBS_XYZ: cp-staging.ct36hfcslmg5.eu-west-2.rds.amazonaws.com
  NEW_RELIC_LICENSE_KEY: eu01xx7895d7f26535be46f75e14245ae5f9NRAL

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 200
  targetMemoryUtilizationPercentage: 200
