# These values apply to the production environment, and overrides config in values.yaml
# as needed.
#
# This values file is applied on each deployment to the environment by AWS Codepipeline.
#
env:
  XYZ_ENV: production
  MONGO_URL: mongodb+srv://cp-pl-0.lfxwi.mongodb.net?retryWrites=true&w=3&readPreference=nearest
  DBS_XYZ: postgres://map-production.ct36hfcslmg5.eu-west-2.rds.amazonaws.com/map
  NEW_RELIC_LICENSE_KEY: eu01xx25a8db3b00741d64d4e895e22794c4NRAL

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 200
  targetMemoryUtilizationPercentage: 200
